### ISSUE TITLE
Aperçu thème

### ISSUE THREAD

**Issue by alexandre-stimpfling** [Clemweb/clemweb#12]
Hello,
Dans la gestion des thèmes, lorsque l'on clique sur le lien d'aperçu d'un thème, ce dernier s'ouvre dans une nouvelle fenêtre avec en url la variable précisant le thème (ex : mondomaine.fr/?theme=default). Le problème est que ça ne fait pas juste activer un aperçu mais il reste actif même lorsque la variable "theme" n'est plus présente dans l'url... Il faut donc ensuite cliquer sur l'aperçu du thème que l'on souhaite pour le ré-activer. Cette fonction d'aperçu à donc un souci.

A+

**Comment by CSI68** [comment]
OK normal
