### ISSUE TITLE
Erreur lors du chargement du widget "Gallery"

### ISSUE THREAD

**Issue by alexandre-stimpfling** [Clemweb/clemweb#14]
**Lorsque j'inclus le widget (overridé dans mon thème) dans "aside.html" de la façon suivante il ne s'affiche pas :**
{{ include('widget_photogallery_gallery.html', ignore_missing=true) }}

**Voici les erreurs affichés :**
Notice: Undefined index: id_gallery in /home/clients/d418a1c0bd44e66165cd743efc027858/clemwebtest/modules/photogallery/front/widget_gallery.php on line 24

Notice: Undefined property: stdClass::$id_gallery in /home/clients/d418a1c0bd44e66165cd743efc027858/clemwebtest/modules/photogallery/front/widget_gallery.php on line 27

**Comment by CSI68** [comment]
{{ include('widget_photogallery_gallery.html', {id_gallery:15}, ignore_missing=true) }}
