### ISSUE TITLE
Problème ajout de Mots clés

### ISSUE THREAD

**Issue by alexandre-stimpfling** [Clemweb/clemweb#15]
Hello,

Le premier mot clé est pris en compte mais je n'arrive pas à en ajouter plus.
Je rentre mon texte et j'appui sur "entrée" mais il ne s'ajoute pas.

Voici l'endroit ou le bug est présent :
http://screencast-o-matic.com/watch/cbhvjPXGrH

A+

**Comment by CSI68** [comment]
Essayer d'ajouter la touche ENTER

**Comment by Clemweb** [comment]
Impossible de binder la touche 'Enter' car le plugin la catch déjà en amont. Du coup j'ai améliorer un peu le process et j'indique dans le comment qu'il faut valider le nouveau mot clef par ','
