### ISSUE TITLE
Souci widgets calendar

### ISSUE THREAD

**Issue by alexandre-stimpfling** [Clemweb/clemweb#16]
Lorsque j'inclu le widget overridé dans mon thème :

Warning: include(/home/clients/d418a1c0bd44e66165cd743efc027858/clemwebtest/src/lib/../../modules/blog/front/widget_calendar_ajax.php): failed to open stream: Aucun fichier ou dossier de ce type in /home/clients/d418a1c0bd44e66165cd743efc027858/clemwebtest/src/lib/clemweb.class.php on line 6095

Warning: include(): Failed opening '/home/clients/d418a1c0bd44e66165cd743efc027858/clemwebtest/src/lib/../../modules/blog/front/widget_calendar_ajax.php' for inclusion (include_path='.:/opt/php7.1/lib/php') in /home/clients/d418a1c0bd44e66165cd743efc027858/clemwebtest/src/lib/clemweb.class.php on line 6095

Le widget "widget_blog_calendar.html" à un affichage incohérent et semble bien bugé, il y a des flêches g/d mais rien ne se passe...

Aperçu :
https://gyazo.com/388afdde36bc14de5463f6d857e6dc9d

**Comment by Clemweb** [comment]
Corrigé 1.6
