### ISSUE TITLE
Ajout d'article Blog impossible

### ISSUE THREAD

**Issue by alexandre-stimpfling** [Clemweb/clemweb#19]
Lorsque je veux ajouter un article de blog et que je l'enregistre j'ai une erreur "Une erreur c'est produite lors de l'enregistrement du post". Je ne peux rajouter aucun nouvel article...

Edit : En fait il me les créé bien...ils sont présents dans la liste des articles mais jette un oeil c'est pas normal car ça empêche d'éditer l'article en restant dessus après l'avoir "enregistré".

**Comment by Clemweb** [comment]
Corrigé
