### ISSUE TITLE
Erreur : Array to string conversion sur le module Library

### ISSUE THREAD

**Issue by alexandre-stimpfling** [Clemweb/clemweb#6]
Salut,

Lorsque j'ouvre le module Library (en direct via le module "Library" ou via la recherche d'un fichier dans un module) j'ai l'erreur suivante "Array to string conversion" et l'explorateur de fichier ne fonctionne pas.
Cette erreur se présente sur le nouvel hébergement.

A+

**Comment by Clemweb** [comment]
Spécifique 1.6, corrigé avec Moxiemanager 2.1.7
