### ISSUE TITLE
Pages en 404 et certains menu sans lien

### ISSUE THREAD

**Issue by alexandre-stimpfling** [Clemweb/clemweb#7]
La majorité des liens de menu que j'ai créé sont en 404. Je pense qu'il y a des soucis de droits ou encore quelques petites choses à corriger par rapport à cet hébergement.
J'ai aussi créé un lien via pagemanager vers le "blog". Ce dernier pointe vers rien... Je ne vois pas ou j'ai pu faire une erreur.
Tout ça marche correctement sur le clemweb hébergé chez toi.

**Comment by Clemweb** [comment]
Plusieurs choses:
- sur la home tu as associé la page avec le module Blog par conséquent l'url d'accès bien la racine pour ce module. C'est pourquoi la 2ème page Blog pointe sur la home. j'ai donc enlevé le module Blog de la home.
- Pour le module album photo : j'ai oublié surement de générer le fichier HTaccess à l'installation. Je l'ai fait et ca a corrigé cette 404 (via le menu dahsboard->outils)
- sur la page du formulaire il y avait une erreur non bloquant lié au captcha qui était activé alors qu'il n'y avait pas de clef installée. J'ai corrigé cela.

**Comment by alexandre-stimpfling** [comment]
Top ! Merci ;-)
